### ISSUE TITLE
Do we need some change or improvement on output, or #:mode?

### ISSUE THREAD

**Issue by yfzhe** [Codewars/codewars-rackunit#5] opened 2019-04-05 02:40 UTC
Trying to solve some katas with Racket, I find some tests seem be weird. For example, in <https://www.codewars.com/kata/1-slash-n-cycle/train/racket>, you can see the test writer make a `dotest` function, displaying the param, actual, and expected. Those information would be displayed in LOG, neither PASS nor FAILED. 

I think this might be because the writer don't know how to use rackunit, and our `codewars/rackunit` wrapper.

I would like to add a new behavior to the `#:mode` argument. Beside the 'quiet, 'simple, etc symbol, the argument can be a list of symbols. If it is a list, `run-tests` will use these symbols as the name of target `check-info`s. So test writes can make more custom output of test results.

After the `run-tests` api being stable, I will write some document about it, which maybe would be helpful to let test writers know how to use this better.

**Comment by kazk** [comment] 2019-04-05 03:08
> I think this might be because the writer don't know how to use rackunit

He writes tests that way in _every language_ and I personally don't like it. Tests should be written in a way that makes most sense in the language.

> I would like to add a new behavior to the `#:mode` argument. Beside the 'quiet, 'simple, etc symbol, the argument can be a list of symbols. If it is a list, `run-tests` will use these symbols as the name of target `check-info`s. So test writes can make more custom output of test results.

I'm not against it.

**Comment by yfzhe** [comment] 2019-04-05 03:23
> He writes tests that way in every language

So it seems not a language-specific problem? Maybe it should be solved at the aspect of the community.

I will still document the `run-tests` function as soon as possible.

**Comment by kazk** [comment] 2019-04-05 03:33
@g964 can you start writing more idiomatic tests for each language and avoid your `dotest`? Each test framework have standard ways to write tests and have best practices. Your kata are solved by many and they also learn from your tests. So please consider learning each test framework before translating and try to write test that fits the framework. If the documentation is lacking or if you need help finding them, please open issues and ask.

**Comment by g964** [comment] 2019-04-05 10:13
@kazk 
First I have to say I saw your post by pure luck:
On <https://gitter.im/Codewars/codewars.com> the right panel where we could saw the CW posts is stuck since days and days at #1709.

I am sorry if you don't like my `dotest` functions:-(
Tests have very different behaviors through languages; most often they don't give inputs, they don't give actual and expected when the test succeeds, they only give cryptic infos when the test fails.

You know I translate my own kata a lot. A simple wrapper like `dotest` give me some uniformity, efficiency and ease.
When I have written it for each specific language I can use, with a slight bit of changes from one language to another, the effective languages tests.

The function `dotest` is, as far as I can tell, idiomatic: it uses the form of the test function of the given language and if I have to use (run-tests (test-suite and so on in Racket for example I evidently use them
for the tests.

I propose that CW gives a wrapper in the spirit of  a better `dotest` for each language; with such a wrapper all languages would give the same info : input, actual, expected for succeeded or failing tests without lots of unfortunate and cumbersome `console.log`.
It would simplify authors' work and give some uniformity to the logs.

**Comment by yfzhe** [comment] 2019-04-05 15:51
As a contributor of the repo, I have to admit that the document is lack (and I'm going to fill this lack, of course), and only if you followed every discuss here, you would know what `run-tests` can do.

In Rackunit, which this repo wraps, input, actual, expected and lots of information about the check, called `check-info`s,  is available. And in the some modes of our `run-tests`, these information can be displayed (when the check is failed). 

Before the PR #6 , there is a 'custom mode of `run-tests`, and in this mode, `run-tests` displays also location information. I added it because I thought it would let us know there the failed check be. However, in a helper **function** producing checks, those location information lost. So I remove it in the #6 .  

I don't know the situation of other languages. But I know, you will have such a "better" `dotest` in Racket part, if the #6 is approved and merged. Just adding a `#:mode` argument `'(params expected actual)` will fit your need. Furthermore, if you can do more customization via `with-check-info`.

**Comment by g964** [comment] 2019-04-05 17:15
@yfzhe All that seems encouraging but I am convinced that a good wrapper adapted to each language  will help everybody. As far as I know (but my learning is certainly insufficient)  there is no uniformity through languages; it seems that units tests have been adapted by each repo contributor with little or no coherence between them.

**Comment by kazk** [comment] 2019-04-05 19:02
@g964 don't get me wrong, I do appreciate your contributions. You're usually one of the first to translate to new languages and your kata are solved by many. As a maintainer of the code runner service, I really appreciate it. Thanks for all the work.

I understand why `dotest` will make the life easier for the authors and the translators. I also agree that many languages and test frameworks requires more work to show a decent output. This is Codewars' limitation and we need to improve.

What I'm asking is to start _considering_ to write the tests as designed _whenever possible_. If you run into limitations, please open an issue and let us know. We can at least discuss about it and possibly find a decent way. Languages have beta period for this reason. We need your feedback.
Also, please spend some time to learn the language and its test framework before translating your popular kata. For example, I've seen your TypeScript translations require a static method in a class like Java rather than a simple function.

For the uniformity across languages, that's not going to happen. Codewars optimizes for more natural experience within the language. If we wanted uniformity, we should be using stdin/stdout format like other platforms or only allow testing through some wrapper like you suggested.
Tests should be written similar to how it's written outside of Codewars when it's possible. Can you at least try to do that for sample tests? It's sometimes hard to work with when you have `dotest(1, 1, 1, 2)` inside a sample test case. We can read what `dotest` does, but it's a distraction and I don't think sample tests need a wrapper to show the inputs.

**Comment by g964** [comment] 2019-04-06 06:58
@kazk Thanks for your explanations and sorry to bother you with my efficiency problems.

When I speak of uniformity I mean that the tests should have the same behavior in, for example,  showing input, actual, expected whenever the tests succeed of fail. Some languages don't output anything, some others flood you with lots of console.log.
> It's sometimes hard to work with when you have dotest(1, 1, 1, 2)

I think it is easier to read `dotest(1, 1, 2)` than to read 
```
describe "Example"
        [ fuzz2 Fuzz.int Fuzz.int "add" <|
            \a b ->
                Example.add a b
                    |> Expect.equal (a + b)
        ]
```
and easier to write `dotest(1, 1, 2)`  in each language than
```
@fact multiply(1, 2) --> 1*2 "multiply(1, 2)"
```
in one language and
```
Assert.AreEqual("1, 2", multiply(1, 2));
```
in another one and
```
cr_assert_eq(multiply(1, 1), 2);
```
in a third one; this  last one giving you no info unless it fails.
> Tests should be written similar to how it's written outside of Codewars when it's possible. 

On my computer I write the tests with, guess what?-) ... `dotest`.
Last thing which has nothing to do with tests:

>  I've seen your TypeScript translations require a static method in a class like Java rather than a simple function.

When I have written my first TS translation I took model in the existing TS translation, they were written that way and have been approved so I thought it was the correct way to use at CW... At the beginning I made the same error with C++:-(

Finally I beg your pardon for being only a true amateur. Have a good day!

**Comment by error256** [comment] 2019-04-06 18:48
There shouldn't be any problems with using `dotest` in most languages, just do the right thing in it.
Racket. Was:
```racket
(let ([actual (cycli n)])   
  (printf "n = ~a\n" n)
  (printf "actual = ~a\n" actual)
  (printf "expect = ~a\n" expect)
  (check-equal? actual expect)    
  (println "*")
)
```
Became:
```racket
(let ([actual (cycli n)])
  (check-equal? actual expect (format "for n = ~a" n))
)
```
Or showing every test (only innermost `test-suite` headers are shown):
```racket
(let ([actual (cycli n)])
  (test-suite
   (format "n = ~a" n)
   (check-equal? actual expect)
))
```
C. Was:
```c
int ans = cycle(n);
cr_assert_eq(exp, ans, "");
```
Became:
```c
int ans = cycle(n);
cr_assert_eq(exp, ans, "n = %d: expected %d, got %d", n, exp, ans);
```
Groovy. Built-in `assert` has the most advanced error messages of all languages.
```groovy
int actual = Cycle.cycle(n);
assertEquals(expected, actual);
```
became:
```groovy
assert Cycle.cycle(n) == expected
```
etc

**Comment by kazk** [comment] 2019-04-06 22:44
@g964 I apologize for my TypeScript comment. It just came into my mind, but I shouldn't have included it. Codewars should have better ways to collaborate so we can ask for help and review more easily to prevent it from being approved instead.

> On my computer I write the tests with, guess what?-) ... `dotest`.

Fair enough. @error256's comment explains what bothers me. It shouldn't matter much if you use `dotest` or not if the output is good.

I'm just asking you to explore little bit. See how the output looks like and improve it _when it's possible_. Ask for help and feedback from users who knows the language and the test framework before assuming there's no better way.

Most importantly, **please let me know** if there's something that can be improved/fixed on the runner side instead of silently trying to workaround. It's not always possible to fix/improve, but I'd like to know so I can at least try.

---

Here's an example with Elixir to show possible alternatives (and a flaw in the current test reporter :disappointed:).

From [Mumbling](https://www.codewars.com/kata/mumbling/elixir) kata:
```elixir
defmodule MumblingTest do
  use ExUnit.Case
  
  defp testing(numtest, s, ans) do 
    IO.puts("Test #{numtest} \n")
    assert Mumbling.accum(s) == ans
  end
  
  test "accum" do 
    testing 1, "ZpglnRxqenU", "Z-Pp-Ggg-Llll-Nnnnn-Rrrrrr-Xxxxxxx-Qqqqqqqq-Eeeeeeeee-Nnnnnnnnnn-Uuuuuuuuuuu"
    testing 2, "NyffsGeyylB", "N-Yy-Fff-Ffff-Sssss-Gggggg-Eeeeeee-Yyyyyyyy-Yyyyyyyyy-Llllllllll-Bbbbbbbbbbb"  
  end
end
```

![image](https://user-images.githubusercontent.com/639336/55675114-99b80200-5872-11e9-89ac-16110f532940.png)

- The output is not great to begin with (**test reporter issue** which I'll look into)
- Using `IO.puts` is not good because the output is not grouped within the test case. It's outside of the test reporter's control if I remember correctly. There might be some way to capture the output and attach it to the test case, but it currently doesn't.
- The input is not shown
- Messy output when passing because it outputs `Test 1`, `Test 2`, etc. If the number of tests passed are useful, consider creating separate test cases.
- This can be improved by specifying the `message`. For example, `assert Mumbling.accum(s) == ans, "Mumbling.accum(#{inspect s}) == #{inspect ans}"`

Without `testing`:
```elixir
defmodule MumblingTest do
  use ExUnit.Case
  test "accum" do
    assert Mumbling.accum("ZpglnRxqenU") == "Z-Pp-Ggg-Llll-Nnnnn-Rrrrrr-Xxxxxxx-Qqqqqqqq-Eeeeeeeee-Nnnnnnnnnn-Uuuuuuuuuuu"
    assert Mumbling.accum("NyffsGeyylB") == "N-Yy-Fff-Ffff-Sssss-Gggggg-Eeeeeee-Yyyyyyyy-Yyyyyyyyy-Llllllllll-Bbbbbbbbbbb"
  end
end
```

![image](https://user-images.githubusercontent.com/639336/55675357-329c4c80-5876-11e9-9dd1-af9cfc30b708.png)

- The output is not great :(
- Shows the input, the output, and expected value
- No extra output when passing
- This works for simple cases with literal input and output, but it can be annoying depending on the tests.

Data driven approach:
```elixir
defmodule MumblingTest do
  use ExUnit.Case
  test "accum" do 
    tests = [
      {"ZpglnRxqenU", "Z-Pp-Ggg-Llll-Nnnnn-Rrrrrr-Xxxxxxx-Qqqqqqqq-Eeeeeeeee-Nnnnnnnnnn-Uuuuuuuuuuu"},
      {"NyffsGeyylB", "N-Yy-Fff-Ffff-Sssss-Gggggg-Eeeeeee-Yyyyyyyy-Yyyyyyyyy-Llllllllll-Bbbbbbbbbbb"} 
    ]

    for {input, expected} <- tests do
      actual = Mumbling.accum(input)
      message = """
      Mumbling.accum(#{inspect input})
      expected:  #{inspect expected}
      got:       #{inspect actual}
      """
      assert actual == expected, message
    end
  end
end 
```

![image](https://user-images.githubusercontent.com/639336/55675124-d8e65300-5872-11e9-9301-ff22587c044f.png)

- The output is not great :(
- Custom message to show whatever
- Uses `assert`'s `message` so it'll be displayed better when the reporter is improved.
- No extra output when passing

---

My point is that there's different ways to write tests and it should be _optimized for the users trying to solve_. By using features from the test framework when you can, it's possible to have the output improved when the test reporter is improved.

**Comment by g964** [comment] 2019-04-07 06:19
@kazk No problem with your comment about TS!
I will try my best to improve the tests and thanks for your explanations!
@error256 Thanks!

**Comment by kazk** [comment] 2019-04-08 07:33
#6 is deployed

**Closed as completed by kazk** 2019-04-08 07:33 UTC
Labels: enhancement
